rules:
    indentation:
        - 4
        -
          size: 4
    force-element-nesting: 0
    force-attribute-nesting: 0
    nesting-depth:
        - 2
        -
          max-depth: 3
    no-color-literals: 0
    no-qualifying-elements: 0
    no-vendor-prefixes:
        - 2
        -
          ignore-non-standard: 1
